# Generated by Django 4.1.6 on 2023-04-24 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyBank', '0002_district'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Branch', models.CharField(max_length=255)),
                ('District', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyBank.district')),
            ],
        ),
    ]
