# Generated by Django 4.1.6 on 2023-04-25 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyBank', '0004_applicationmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationmodel',
            name='Email',
            field=models.EmailField(max_length=255, null=True),
        ),
    ]
