# Generated by Django 4.1.6 on 2023-04-25 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyBank', '0005_applicationmodel_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationmodel',
            name='Phone',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
